# Generated by Django 2.2.3 on 2019-07-18 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20190713_1823'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='link',
            field=models.URLField(default=0, max_length=512),
            preserve_default=False,
        ),
    ]
