# Generated by Django 2.2.3 on 2019-07-18 13:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_post_tag'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='link',
        ),
        migrations.RemoveField(
            model_name='post',
            name='tag',
        ),
    ]
