# Generated by Django 2.2.3 on 2019-07-18 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_auto_20190718_1917'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='link',
            field=models.URLField(default=1, max_length=512),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='post',
            name='tag',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
