# Generated by Django 2.2.3 on 2019-07-18 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0017_remove_post_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='downloads',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
