# Generated by Django 2.2.3 on 2019-07-18 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0018_post_downloads'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='downloads',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
