# Generated by Django 2.2.3 on 2019-07-18 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0022_auto_20190718_2113'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='downloads',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
