# Generated by Django 2.2.3 on 2019-07-18 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0023_auto_20190718_2116'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='posts',
            name='downloads',
        ),
        migrations.AddField(
            model_name='posts',
            name='files',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
