# Generated by Django 2.2.3 on 2019-07-19 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0026_auto_20190719_1125'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='tag',
            field=models.CharField(choices=[('PG-TRB', 'PG-TRB'), ('POLY-TRB', 'POLY-TRB'), ('ENGR-TRB', 'ENGR-TRB'), ('TNSET', 'TNSET')], max_length=255),
        ),
    ]
